[debug]
	# Nombre: Modo de Depuración
	# Descripción: Activar modo de depuración.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	debugMode = false

	# Nombre: GUIs de Depuración
	# Descripción: Activar modo GUIs de depuración.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	debugGuis = false

	# Nombre: Entradas de Depuración
	# Descripción: Activar modo de entradas de depuración.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	debugInputs = false

	# Nombre: Tooltips de Info de Depuración
	# Descripción: Agregar información de depuración a los tooltips de ingredientes cuando están activados los tooltips avanzados.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	debugInfoTooltipsEnabled = false

	# Nombre: Habilitar Ítems de Prueba que Crashean
	# Descripción: Agrega ingredientes a JEI que causan crash intencionalmente, para ayudar con la depuración.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	crashingTestItemsEnabled = false

	# Nombre: jei.config.debug.debug.crashingTestRecipesEnabled
	# Descripción: jei.config.debug.debug.crashingTestRecipesEnabled.description
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	crashingTestRecipesEnabled = false

	# Nombre: Registrar Estadísticas de Árboles de Sufijos
	# Descripción: Registrar información sobre los árboles de sufijos usados para las búsquedas, para ayudar en la depuración.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	logSuffixTreeStats = false


