[appearance]
	# Nombre: Centrar Barra de Búsqueda
	# Descripción: Mueve la barra de búsqueda de JEI al centro inferior de la pantalla.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	centerSearch = false

	# Nombre: Altura de la GUI de Recetas
	# Descripción: Altura máxima de la interfaz de recetas (en píxeles).
	# Valores válidos: Any integer greater than or equal to 175
	# Valor predeterminado: 350
	recipeGuiHeight = 350


[cheating]
	# Nombre: Modo de Entrega
	# Descripción: Elegí si JEI debería darte los ingredientes directo al inventario o levantarlos con el mouse.
	# Valores válidos: [INVENTORY, MOUSE_PICKUP]
	# Valor predeterminado: MOUSE_PICKUP
	giveMode = MOUSE_PICKUP

	# Nombre: Trampear a la Hotbar con Atajos
	# Descripción: Habilita que se puedan poner ítems en la hotbar usando Shift + números.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	cheatToHotbarUsingHotkeysEnabled = false

	# Nombre: Mostrar Ingredientes Ocultos
	# Descripción: Muestra ingredientes que no están en el menú creativo.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	showHiddenIngredients = false

	# Nombre: Mostrar Recetas por Tags
	# Descripción: Muestra recetas relacionadas a etiquetas de ítems o bloques.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	showTagRecipesEnabled = false


[bookmarks]
	# Nombre: Agregar Favoritos al Principio
	# Descripción: Si está activado, los nuevos favoritos se agregan al inicio. Si no, al final.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	addBookmarksToFrontEnabled = false

	# Nombre: Arrastrar para Reordenar Favoritos
	# Descripción: Permite reordenar los favoritos arrastrándolos.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	dragToRearrangeBookmarksEnabled = true


[tooltips]
	# Nombre: Funciones de Tooltips en Favoritos
	# Descripción: Funciones adicionales en los tooltips de favoritos.
	# Valores válidos: A comma-separated list containing values of:
	# [PREVIEW, INGREDIENTS]
	# Valor predeterminado: PREVIEW
	bookmarkTooltipFeatures = PREVIEW

	# Nombre: Shift para Tooltips de Favoritos
	# Descripción: Mantené Shift para ver funciones extra en los tooltips de favoritos.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	holdShiftToShowBookmarkTooltipFeatures = true

	# Nombre: Mostrar Nombre de la Pestaña Creativa
	# Descripción: Muestra el nombre de la pestaña creativa en los tooltips de ingredientes.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	showCreativeTabNamesEnabled = false

	# Nombre: Mostrar Contenido de Etiquetas
	# Descripción: Muestra el contenido de etiquetas en los tooltips al ver ingredientes de recetas.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	tagContentTooltipEnabled = true

	# Nombre: Ocultar Etiquetas de un Solo Ingrediente
	# Descripción: Oculta el contenido de etiquetas cuando solo tienen un ingrediente.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	hideSingleTagContentTooltipEnabled = true

	# Nombre: Recipe Ingredient Summary
	# Descripción: Show a summary of ingredients needed for a recipe, on its output ingredient's tooltip.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	enableRecipesGuiIngredientsSummary = false


[performance]
	# Nombre: Búsqueda de Bajo Consumo
	# Descripción: Activa el modo de búsqueda de bajo consumo (usa menos RAM pero es más lento).
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	lowMemorySlowSearchEnabled = false


[lookups]
	# Nombre: Buscar Contenido de Fluidos
	# Descripción: Cuando buscás recetas con ítems que contienen fluidos, también buscá recetas para los fluidos.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	lookupFluidContentsEnabled = false

	# Nombre: Buscar Etiquetas de Ítems/Bloques
	# Descripción: Al buscar etiquetas de ítems, también se incluyen las etiquetas de bloques por defecto contenidas en ellos.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	lookupBlockTagsEnabled = true


[lookupHistory]
	# Nombre: Enabled
	# Descripción: Display or hide the lookup history overlay.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	enabled = false

	# Nombre: Max Rows
	# Descripción: Max number of rows to display in the lookup history overlay.
	# Valores válidos: An integer in the range [1, 7] (inclusive)
	# Valor predeterminado: 2
	maxRows = 2

	# Nombre: Max Ingredients
	# Descripción: Max number of lookup history ingredients to save.
	# Valores válidos: An integer in the range [10, 1000] (inclusive)
	# Valor predeterminado: 100
	maxIngredients = 100

	# Nombre: Display Side
	# Descripción: Side of the screen to display the lookup history overlay.
	# Valores válidos: [LEFT, RIGHT]
	# Valor predeterminado: LEFT
	displaySide = LEFT


[advanced]
	# Nombre: Capturar Errores de Renderizado
	# Descripción: Captura errores de renderizado de ingredientes con mods y trata de recuperarse en lugar de crashear.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	catchRenderErrorsEnabled = true


[input]
	# Nombre: Retardo de Arrastre
	# Descripción: Cantidad de milisegundos antes de que un clic largo se considere como arrastre.
	# Valores válidos: An integer in the range [0, 1000] (inclusive)
	# Valor predeterminado: 150
	dragDelayInMilliseconds = 150

	# Nombre: Velocidad de Desplazamiento Suave
	# Descripción: Velocidad de desplazamiento del mouse en cajas con desplazamiento suave. Medido en píxeles.
	# Valores válidos: An integer in the range [1, 50] (inclusive)
	# Valor predeterminado: 9
	smoothScrollRate = 9


[sorting]
	# Nombre: Etapas de Ordenamiento de Ingredientes
	# Descripción: Orden de clasificación para la lista de ingredientes.
	# Valores válidos: A comma-separated list containing values of:
	# [MOD_NAME, INGREDIENT_TYPE, ALPHABETICAL, CREATIVE_MENU, TAG, ARMOR, MAX_DURABILITY]
	# Valor predeterminado: MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU
	ingredientSortStages = MOD_NAME, INGREDIENT_TYPE, CREATIVE_MENU

	# Nombre: Etapas de Ordenamiento de Recetas
	# Descripción: Orden de clasificación para las recetas mostradas.
	# Valores válidos: A comma-separated list containing values of:
	# [BOOKMARKED, CRAFTABLE]
	# Valor predeterminado: BOOKMARKED, CRAFTABLE
	recipeSorterStages = BOOKMARKED, CRAFTABLE


[search]
	# Nombre: Modo de Búsqueda por @Mod
	# Descripción: Modo de búsqueda para nombres de mods (prefijo: @).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor predeterminado: REQUIRE_PREFIX
	modNameSearchMode = REQUIRE_PREFIX

	# Nombre: Modo de Búsqueda por #Etiqueta
	# Descripción: Modo de búsqueda para etiquetas (prefijo: #).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor predeterminado: REQUIRE_PREFIX
	tagSearchMode = REQUIRE_PREFIX

	# Nombre: Modo de Búsqueda por $Tooltip
	# Descripción: Modo de búsqueda por descripciones emergentes (prefijo: $).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor predeterminado: ENABLED
	tooltipSearchMode = ENABLED

	# Nombre: ^Modo de Búsqueda por Color
	# Descripción: Modo de búsqueda por colores (prefijo: ^).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor predeterminado: DISABLED
	colorSearchMode = DISABLED

	# Nombre: &Modo de Búsqueda por Ubicación de Recurso
	# Descripción: Modo de búsqueda por ubicaciones de recursos (prefijo: &).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor predeterminado: DISABLED
	resourceLocationSearchMode = DISABLED

	# Nombre: %Modo de Búsqueda por Pestaña Creativa
	# Descripción: Modo de búsqueda por nombre de pestañas del modo creativo (prefijo: %).
	# Valores válidos: [ENABLED, REQUIRE_PREFIX, DISABLED]
	# Valor predeterminado: DISABLED
	creativeTabSearchMode = DISABLED

	# Nombre: Buscar en Tooltips Avanzados
	# Descripción: Buscar en tooltips avanzados (visibles con F3 + H).
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	searchAdvancedTooltips = false

	# Nombre: Buscar ID de Mod
	# Descripción: Buscar IDs de mods además de los nombres.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	searchModIds = true

	# Nombre: Buscar Alias de Mod
	# Descripción: Buscar alias (nombres alternativos) de mods agregados por plugins, además de los nombres.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	searchModAliases = true

	# Nombre: Buscar Nombres Cortos de Mods
	# Descripción: Buscar por siglas o letras iniciales del nombre de un mod.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	searchShortModNames = false

	# Nombre: Buscar Alias de Ingredientes
	# Descripción: Buscar alias (nombres alternativos) de ingredientes agregados por plugins, además de los nombres de ingredientes.
	# Valores válidos: [true, false]
	# Valor predeterminado: true
	searchIngredientAliases = true


[ingredientList]
	# Nombre: Filas Máximas
	# Descripción: Cantidad máxima de filas visibles.
	# Valores válidos: An integer in the range [1, 100] (inclusive)
	# Valor predeterminado: 16
	maxRows = 16

	# Nombre: Columnas Máximas
	# Descripción: Cantidad máxima de columnas visibles.
	# Valores válidos: An integer in the range [2, 100] (inclusive)
	# Valor predeterminado: 9
	maxColumns = 9

	# Nombre: Alineación Horizontal
	# Descripción: Alineación horizontal de la lista de ingredientes dentro del área disponible.
	# Valores válidos: [LEFT, CENTER, RIGHT]
	# Valor predeterminado: RIGHT
	horizontalAlignment = RIGHT

	# Nombre: Alineación Vertical
	# Descripción: Alineación vertical de la lista de ingredientes dentro del área disponible.
	# Valores válidos: [TOP, CENTER, BOTTOM]
	# Valor predeterminado: TOP
	verticalAlignment = TOP

	# Nombre: Visibilidad de Navegación
	# Descripción: Visibilidad de los botones superiores. Usá AUTO_HIDE para que se muestren solo si hay varias páginas.
	# Valores válidos: [ENABLED, AUTO_HIDE, DISABLED]
	# Valor predeterminado: ENABLED
	buttonNavigationVisibility = ENABLED

	# Nombre: Mostrar Fondo de Interfaz
	# Descripción: Activá esto para mostrar una textura de fondo detrás de la lista de ingredientes.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	drawBackground = false


[bookmarkList]
	# Nombre: Filas Máximas
	# Descripción: Cantidad máxima de filas visibles.
	# Valores válidos: An integer in the range [1, 100] (inclusive)
	# Valor predeterminado: 16
	maxRows = 16

	# Nombre: Columnas Máximas
	# Descripción: Cantidad máxima de columnas visibles.
	# Valores válidos: An integer in the range [2, 100] (inclusive)
	# Valor predeterminado: 9
	maxColumns = 9

	# Nombre: Alineación Horizontal
	# Descripción: Alineación horizontal de la lista de favoritos dentro del área disponible.
	# Valores válidos: [LEFT, CENTER, RIGHT]
	# Valor predeterminado: LEFT
	horizontalAlignment = LEFT

	# Nombre: Alineación Vertical
	# Descripción: Alineación vertical de la lista de favoritos dentro del área disponible.
	# Valores válidos: [TOP, CENTER, BOTTOM]
	# Valor predeterminado: TOP
	verticalAlignment = TOP

	# Nombre: Visibilidad de Navegación
	# Descripción: Visibilidad de los botones superiores. Usá AUTO_HIDE para que se muestren solo si hay varias páginas.
	# Valores válidos: [ENABLED, AUTO_HIDE, DISABLED]
	# Valor predeterminado: ENABLED
	buttonNavigationVisibility = ENABLED

	# Nombre: Mostrar Fondo de Interfaz
	# Descripción: Activá esto para mostrar una textura de fondo detrás de la lista de favoritos.
	# Valores válidos: [true, false]
	# Valor predeterminado: false
	drawBackground = false


