[modName]
	# Nombre: Formato del Nombre del Mod
	# Descripción: Formato del nombre del mod en los tooltips de las GUIs de JEI. Dejalo vacío para desactivarlo.
	# Valores válidos: A chat formatting string.
	# Use these formatting colors:
	# black dark_blue dark_green dark_aqua dark_red dark_purple gold gray dark_gray blue green aqua red light_purple yellow white
	# With these formatting options:
	# obfuscated bold strikethrough underline italic
	# Valor predeterminado: blue italic
	modNameFormat = blue italic


